export const users = [
  {
    id: 'u1',
    firstName: 'Sandeep',
    middleName: 'Kumar',
    lastName: 'Metta',
    role: 'Senior Product Manager',
    branch: 'Engineering',
  },
  {
    id: 'u2',
    firstName: 'Renil',
    middleName: '',
    lastName: 'Komtila',
    role: 'Technical Lead',
    branch: 'Platform',
  },
  {
    id: 'u3',
    firstName: 'Ajay',
    middleName: 'Kumar',
    lastName: 'Kalicheti',
    role: 'Delivery Manager',
    branch: 'Operations',
  },
  {
    id: 'u4',
    firstName: 'Lina',
    middleName: '',
    lastName: 'Dsouza',
    role: 'Business Analyst',
    branch: 'Strategy',
  },
  {
    id: 'u5',
    firstName: 'Nisha',
    middleName: 'V',
    lastName: 'Iyer',
    role: 'UX Designer',
    branch: 'Design',
  },
]

export const projects = [
  {
    id: 'p1',
    name: 'GIIS Project',
    client: 'Singapore Government',
    status: 'In Progress',
    ownerId: 'u1',
    dateRange: '2022-01-01 to 2028-12-31',
    hours: 120,
    cost: 5000,
  },
  {
    id: 'p2',
    name: 'BlazeUP Project',
    client: 'TerraLogic Software Solutions',
    status: 'Completed',
    ownerId: 'u2',
    dateRange: '2024-02-15 to 2027-08-30',
    hours: 200,
    cost: 8000,
  },
  {
    id: 'p3',
    name: 'Lollipop Project',
    client: 'TerraLogic Software Solutions',
    status: 'In Progress',
    ownerId: 'u3',
    dateRange: '2023-04-01 to 2026-10-15',
    hours: 140,
    cost: 6200,
  },
  {
    id: 'p4',
    name: 'Caramelo Project',
    client: 'TerraLogic Software Solutions',
    status: 'Completed',
    ownerId: 'u4',
    dateRange: '2024-01-10 to 2027-06-20',
    hours: 180,
    cost: 7100,
  },
]
